#!/usr/bin/perl
#====================================================
#        NAME : zabbix-toolbox.pl
#        DATE : 02/02/2018
#      AUTHOR : William FEO
# DESCRIPTION : 
#     VERSION : 1.0
#====================================================

#_____PACKAGES_____
use utf8;
# Encodage
binmode STDIN, ":encoding(utf8)";
binmode STDOUT, ":encoding(utf8)";
binmode STDERR, ":encoding(utf8)";

use FindBin;
use lib "$FindBin::Bin/lib";

use Moo;
use 5.010;
use Getopt::Long qw(GetOptions);
use feature 'say';
use IPC::System::Simple qw(system);
use Cwd;

#_____VARIABLES_____
my $DIR = getcwd;
my $DIR_BIN = "$DIR/bin";

my $BIN_INIT="$DIR_BIN/init.pl";
my $BIN_HOST_CREATE="$DIR_BIN/host_create.pl";
my $BIN_HOSTINVENTORY_UPDATE="$DIR_BIN/hostinventory_update.pl";

my ($init,$fileCreateHosts,$fileUpdateHostInventory,$fileForceUpdateHostInventory,$help) ;

my $STATUS=0;


#_____FUNCTIONS_____
sub fctHelp {
	say "
NOM
	zabbix-toolbox - API pour l'outil de supervision Zabbix version 3.4

SYNOPSIS
	zabbix-toolbox [OPTIONS] [FICHIER]

DESCRIPTION
	zabbix-toolbox est un API permettant de realiser des taches d'administration avec l'outil de supervision Zabbix.

OPTIONS
	Initialisation
		-i, --init
			Initialisation de l'API avec l'adresse du serveur, le nom d'utilisateur et le mot de passe.
			
	Creation
		-cht, --create-host [fichier.csv]
			Procede a la creation massive d'hotes à partir d'un fichier CSV fourni en parametre.
		
	Mise a jour
		-uhi, --update-host-inventory [fichier.csv]
			Procede a la mise a jour massive des champs d'inventaires non renseignes de l'hote a partir du fichier CSV passe en parametre
			
		-fuhi, --force-update-host-inventory [fichier.csv]
			Procede a la mise a jour massive et forcee des champs d'inventaires de l'hote à partir du fichier CSV passe en parametre
			
		-h, --help
			Affiche l'aide
";
}

#_____PROGRAMME_____

GetOptions(
	'init|i'                             => \$init,
	'create-host|cht=s'                  => \$fileCreateHosts,
	'update-host-inventory|uhi=s'        => \$fileUpdateHostInventory,
	'force-update-host-inventory|fuhi=s' => \$fileForceUpdateHostInventory,
	'help|h'                             => \$help
);


if ( defined $init ) {
	my @args = ("$BIN_INIT");
	$STATUS=1;
	system($^X, @args);
} 

if ( defined $fileCreateHosts ) {
	my @args = ("$BIN_HOST_CREATE","$fileCreateHosts");
	$STATUS=1;
	system($^X, @args);
} 

if ( defined $fileUpdateHostInventory ) {
	my @args = ("$BIN_HOSTINVENTORY_UPDATE","0","$fileUpdateHostInventory");
	$STATUS=1;
	system($^X, @args);
}

if ( defined $fileForceUpdateHostInventory ) {
	my @args = ("$BIN_HOSTINVENTORY_UPDATE","1","$fileForceUpdateHostInventory");
	$STATUS=1;
	system($^X, @args);
}

if ( defined $help ) {
	fctHelp;
	$STATUS=1;
}
